name: Eleventy Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: cjerrington/actions-eleventy@master
        with:
          args: '--output=site'
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages
